{
 "title": "New dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Requests per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{service_name=\"demo-app\"}[$__interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_total{service_name=\"demo-app\", status_code=~\"5..\"}[$__interval])) / sum(rate(http_server_requests_total{service_name=\"demo-app\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_request_duration_seconds_bucket{service_name=\"demo-app\"}[$__interval])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"demo-app\"}\n"
    }
   ]
  }
 ]
}